### ISSUE TITLE
Trigger input does match original plaits hardware

### ISSUE THREAD

**Issue by crp500** [sourcebox/mi-plaits-dsp-rs#1]
I own the original plaits hardware from MU and one thing I know for sure (just tested it) is that all original 16 engines (and the 8 new engines) respond to the trigger being patched. There is no need to also patch Level.

My testing of the mi-plaits-dsp-rs crate indicates that only 6 of the engines respond the trigger ONLY being patched.
1. speech
2. string
3. modal
4. kick
5. snare
6. hihat

All other engines appear to respond to Level being patched (modulations_level_patched) and triggering the internal envelope/lpg? via a ping to modulations_level.

level_patched and triggering via modulations_level from the crate/library sounds the same as the hardware engines when triggering via the trigger input so you can do that to get the same or similar sound.

I checked the engine code for each engine and only the 6 mentioned expose the trigger input in the params passed in for rendering.

The manual says this about trigger and level input:

> 3. Trigger input. Serves four percussive purposes:
> Triggers the internal decaying envelope generator.
> Excites the physical and percussive models.
> Strikes the internal low-pass gate (unless the LEVEL CV input [4] is patched).
> Samples and holds the value of the MODEL CV input.
> 
> 4. Level CV input. Opens the internal low-pass gate, to simultaneously control the amplitude and brightness of the output signal. Also acts as an accent control when triggering the physical or percussive models.
> 

I interpret the manual as saying that trigger input (on its own)  works with all engines although maybe in different ways.

I interpret level cv input as accent for physical or percussive models. It dosent seem to behave that way with the crate.
modulations_Level does seem to strike the lowpass gate when modulations_level_patched. 

I am intested in how others interpret the manual on triggering

**Comment by sourcebox** [comment]
Closed via [9fd5564](https://github.com/sourcebox/mi-plaits-dsp-rs/commit/9fd5564e0abfddde51f5c6782975f95519ad4c9c)
